### ISSUE TITLE
Discrepancy with a test case

### ISSUE THREAD

**Issue by rnehra01** [jaybosamiya/cryptopals-solutions#1] opened 2016-12-05 08:05 UTC
I don't know exactly it can be one of the test-case for the unpad function but according to me, code should consider the case "ICE ICE BABY\x05\x05\x05\x05\x05" padding length(5) is incorrect instead of 4.Your code isn't considering that.

**Comment by jaybosamiya** [comment] 2016-12-07 15:36
The unpad function in my code is the following:
```
def unpad(data, blocksize=16):
    if len(data) % blocksize != 0:
        raise Exception
    must_unpad = ord(data[-1])
    if must_unpad < 0 or must_unpad > blocksize:
        raise Exception
    if data[-must_unpad:] != chr(must_unpad) * must_unpad:
        raise Exception
    return data[:-must_unpad]
```
While the exceptions thrown are not too descriptive (and could probably be replaced as assertions instead), the code basically does the following:
+ Check if data is a multiple of block size
+ Check if last byte is a valid "padding byte"
+ Ensure that last few bytes are valid padding
+ Strip valid padding

The string that you have provided fails the first check and hence throws an exception. I do not see what the issue is then. I'm closing this issue since it is working as expected, but feel free to comment if you feel I have misunderstood your issue.

**Closed as completed by jaybosamiya** 2016-12-07 15:36 UTC

**Comment by jaybosamiya** [comment] 2016-12-07 15:41
Oh wait, I just noticed that you have opened an issue on an old solution for cryptopals that I had.
I have not looked into this code over 1+ year, and instead work on cryptopals from this repo: https://github.com/jaybosamiya/matasano-crypto

This repo (https://github.com/jaybosamiya/cryptopals-solutions) is old and outdated, and is kept here only for archival reasons. The newer repo (https://github.com/jaybosamiya/matasano-crypto) is much cleaner and has better readability as well.
